var items = {
    //                      Armours
    Nothing: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        weight: 0,
        excludes: [],
        type: 'normal',
    },
    INTERCEPTOR: {
        hp: 860,
        heat: 265,
        cooling: 80,
        energy: 193,
        engRegen: 56,
        psyResist: 16,
        electricResist: 22,
        explosionResist: 22,
        weight: 309,
        excludes: [],
        type: 'normal',
    },
    ARCHIMOND_L: {
        hp: 1090,
        heat: 265,
        cooling: 76,
        energy: 265,
        engRegen: 76,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 22,
        weight: 363,
        excludes: [],
        type: 'normal',
    },
    AVENGER: {
        hp: 1242,
        heat: 145,
        cooling: 48,
        energy: 193,
        engRegen: 64,
        psyResist: 16,
        electricResist: 22,
        explosionResist: 22,
        weight: 350,
        excludes: [],
        type: 'normal',
    },
    NIGHTMARE: {
        hp: 879,
        heat: 290,
        cooling: 96,
        energy: 193,
        engRegen: 64,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 16,
        weight: 315,
        excludes: [],
        type: 'normal',
    },
    BRUTALITY: {
        hp: 1033,
        heat: 290,
        cooling: 88,
        energy: 217,
        engRegen: 64,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 16,
        weight: 341,
        excludes: [],
        type: 'normal',
    },
    WINDIGO: {
        hp: 982,
        heat: 301,
        cooling: 112,
        energy: 217,
        engRegen: 72,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 16,
        weight: 345,
        excludes: [],
        type: 'normal',
    },
    ZARKARES: {
        hp: 1136,
        heat: 312,
        cooling: 112,
        energy: 193,
        engRegen: 64,
        psyResist: 16,
        electricResist: 16,
        explosionResist: 24,
        weight: 362,
        excludes: [],
        type: 'normal',
    },
    SITH: {
        hp: 930,
        heat: 193,
        cooling: 64,
        energy: 245,
        engRegen: 112,
        psyResist: 22,
        electricResist: 16,
        explosionResist: 22,
        weight: 321,
        excludes: [],
        type: 'normal',
    },
    GRIMREAPER: {
        hp: 879,
        heat: 193,
        cooling: 64,
        energy: 346,
        engRegen: 112,
        psyResist: 22,
        electricResist: 16,
        explosionResist: 22,
        weight: 329,
        excludes: [],
        type: 'normal',
    },
    NAGA: {
        hp: 982,
        heat: 193,
        cooling: 72,
        energy: 279,
        engRegen: 104,
        psyResist: 22,
        electricResist: 16,
        explosionResist: 22,
        weight: 335,
        excludes: [],
        type: 'normal',
    },
    Molten_platinum_vest: {
        hp: 982,
        heat: 267,
        cooling: 96,
        energy: 193,
        engRegen: 64,
        psyResist: 44,
        electricResist: 22,
        explosionResist: 16,
        weight: 346,
        excludes: [],
        type: 'normal',
    },
    Lightning_Platinum_Vest: {
        hp: 982,
        heat: 193,
        cooling: 64,
        energy: 267,
        engRegen: 96,
        psyResist: 44,
        electricResist: 16,
        explosionResist: 22,
        weight: 346,
        excludes: [],
        type: 'normal',
    },
    //                     Legs
    GRAVE_DIGGERS: {
        hp: 287,
        weight: 123,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    IRON_BOOTS: {
        hp: 478,
        weight: 138,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    ROLLING_BEASTS: {
        hp: 451,
        weight: 134,
        walking: 3,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    THE_CLAW: {
        hp: 860,
        weight: 150,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    SCORCHING_FEET: {
        hp: 413,
        weight: 120,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    DEVOURING_PAWS: {
        hp: 394,
        weight: 121,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    SPARKED_RUNNERS: {
        hp: 363,
        weight: 114,
        walking: 3,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    DYNAMIC_STOMPERS: {
        hp: 372,
        weight: 118,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    CHARGED_WALKERS: {
        hp: 413,
        weight: 122,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    LIGHTNING_SUPPORTERS: {
        hp: 413,
        weight: 124,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    DYNAMITE_BOOTS: {
        hp: 413,
        weight: 136,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
    },
    //                   Modules
    HEAT_ENGINE: {
        hp: 0,
        heat: 89,
        cooling: 42,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 25,
        excludes: [],
        type: 'normal',
    },
    HEAT_STORAGE_UNIT_L: {
        hp: 0,
        heat: 134,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 22,
        excludes: [],
        type: 'normal',
    },
    COOLING_MASS_BOOSTER: {
        hp: 0,
        heat: 0,
        cooling: 63,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 15,
        excludes: [],
        type: 'normal',
    },
    ENERGY_ENGINE: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 89,
        engRegen: 42,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 25,
        excludes: [],
        type: 'normal',
    },
    ENERGY_STORAGE_UNIT_L: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 134,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 22,
        excludes: [],
        type: 'normal',
    },
    ENERGY_MASS_BOOSTER: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 63,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 15,
        excludes: [],
        type: 'normal',
    },
    PLATINUM_PLATING_L: {
        hp: 315,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 40,
        excludes: [],
        type: 'normal',
    },
    Iron_Plating__Epic: {
        hp: 145,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 40,
        excludes: [],
        type: 'normal',
    },
    MAXIMUM_PROTECTOR_L: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 39,
        electricResist: 39,
        explosionResist: 39,
        weight: 51,
        type: 'general',
        excludes: ['general', 'psyhic', 'electric', 'hot'],
    },
    Savior_Resistance: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 16,
        electricResist: 16,
        explosionResist: 16,
        weight: 51,
        type: 'general',
        excludes: ['general', 'psyhic', 'electric', 'hot'],
    },
    MIGHTY_PROTECTOR_L: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 59,
        electricResist: 0,
        explosionResist: 0,
        weight: 28,
        type: 'psyhic',
        excludes: ['general', 'psyhic'],
    },
    Physical_Protector: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 24,
        electricResist: 0,
        explosionResist: 0,
        weight: 28,
        type: 'psyhic',
        excludes: ['general', 'psyhic'],
    },
    SUPERCHARGE_PROTECTOR_L: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 59,
        explosionResist: 0,
        weight: 28,
        type: 'electric',
        excludes: ['general', 'electric'],
    },
    Energy_Protector: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 24,
        explosionResist: 0,
        weight: 28,
        type: 'electric',
        excludes: ['general', 'electric'],
    },
    ULTRAHOT_PROTECTOR_L: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 59,
        weight: 28,
        type:'hot',
        excludes: ['general', 'hot'],
    },
    Heat_Protector: {
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 24,
        weight: 28,
        type:'hot',
        excludes: ['general', 'hot'],
    },
    //                              Side Weapons
    Nothing_R: {
        weight: 0,
        excludes: [],
        type: 'normal',
    },
    ABOMINATION_L: {
        weight: 70,
        excludes: [],
        type: 'normal',
        attackType: 'rocket',
        minDamage:212,
        maxDamage:307,
        heatDamage:71,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:12,
        psyResistDrain:0,
        uses:3,
        push:1,
        heatCost:44,
        energyCost:19,
        damageIco:'explosion',
        color:'red',

    },
    ANNIHILATION: {
        weight: 65,
        excludes: [],
        type: 'normal',
        attackType: 'bullet',
        minDamage:203,
        maxDamage:341,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:15,
        uses:3,
        push:0,
        heatCost:0,
        energyCost:0,
        damageIco:'psyhical',
        color:'yellow',

    },
    ARMOR_ANNIHILATOR_L: {
        weight: 17,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:41,
        maxDamage:44,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:40,
        uses:1,
        push:0,
        heatCost:0,
        energyCost:0,
        damageIco:'psyhical',
        color:'yellow',
    },
    ARMOR_DISSOLVER_L: {
        weight: 18,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:41,
        maxDamage:55,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:2,
        push:3,
        heatCost:62,
        energyCost:0,
        damageIco:'psyhical',
        color:'yellow',

    },
    ASH_CREATOR_L: {
        weight: 58,
        excludes: [],
        type: 'normal',
        attackType: 'flame',
        minDamage:163,
        maxDamage:213,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:180,
        totalEnergyDamage:48,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:3,
        push:0,
        heatCost:31,
        energyCost:93,
        damageIco:'electric',
        color:'blue',

    },
    BACKBREAKER: {
        weight: 44,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:228,
        maxDamage:408,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:8,
        energyDamage:180,
        totalEnergyDamage:48,
        energyRegenDamage:8,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:1,
        heatCost:31,
        energyCost:31,
        damageIco:'psyhical',
        color:'yellow',
    },
    BIGDADDY_L: {
        weight: 53,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:203,
        maxDamage:265,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:16,
        energyCost:47,
        damageIco:'electric',
        color:'blue',

    },
    BLOODWEEP_L: {
        weight: 34,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:147,
        maxDamage:209,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:20,
        uses:3,
        push:0,
        heatCost:31,
        energyCost:31,
        damageIco:'psyhical',
        color:'yellow',

    },
    BRIGHTROAR_L: {
        weight: 45,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:193,
        maxDamage:311,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:103,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:9,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:13,
        energyCost:50,
        damageIco:'electric',
        color:'blue',
    },
    BULLDOG_L: {
        weight: 73,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:182,
        maxDamage:406,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:67,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:10,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:3,
        push:1,
        heatCost:0,
        energyCost:31,
        damageIco:'electric',
        color:'blue',
    },
    BUNKER_SHELLL: {
        weight: 50,
        excludes: [],
        type: 'normal',
        attackType: 'rocket',
        minDamage:243,
        maxDamage:463,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:123,
        totalEnergyDamage:30,
        energyRegenDamage:17,
        eleResDrain:13,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:1,
        push:1,
        heatCost:0,
        energyCost:31,
        damageIco:'electric',
        color:'blue',
    },
    CHAOS_BRINGER_L: {
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:203,
        maxDamage:265,
        heatDamage:71,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:47,
        energyCost:16,
        damageIco:'explosion',
        color:'red',
    },
    CORRUPT_LIGHT: {
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage:140,
        maxDamage:236,
        heatDamage:93,
        totalHeatDamage:24,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:47,
        energyCost:16,
        damageIco:'explosion',
        color:'red',
    },
    CRIMSON_RAPTURE_L: {
        weight: 58,
        excludes: [],
        type: 'normal',
        attackType: 'flame',
        minDamage:163,
        maxDamage:213,
        heatDamage:135,
        totalHeatDamage:48,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:3,
        push:0,
        heatCost:93,
        energyCost:31,
        damageIco:'explosion',
        color:'red',
    },
    DAWNBLAZE: {
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:203,
        maxDamage:265,
        heatDamage:71,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:5,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:47,
        energyCost:16,
        damageIco:'explosion',
        color:'red',
    },
    EMP: {
        weight: 70,
        excludes: [],
        type: 'normal',
        attackType: 'bomb',
        minDamage:37,
        maxDamage:61,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:334,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:1,
        push:0,
        heatCost:0,
        energyCost:393,
        damageIco:'electric',
        color:'blue',
    },
    FLAMINATOR: {
        weight: 47,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:148,
        maxDamage:228,
        heatDamage:93,
        totalHeatDamage:24,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:0,
        energyCost:110,
        damageIco:'explosion',
        color:'red',
    },
    Flaming_hammer: {
        weight: 60,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:211,
        maxDamage:354,
        heatDamage:86,
        totalHeatDamage:0,
        coolingDamage:17,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:3,
        heatCost:50,
        energyCost:13,
        damageIco:'explosion',
        color:'red',
    },
    HEAT_BOMB: {
        weight: 50,
        excludes: [],
        type: 'normal',
        attackType: 'bomb',
        minDamage:40,
        maxDamage:59,
        heatDamage:393,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:1,
        push:0,
        heatCost:393,
        energyCost:0,
        damageIco:'explosion',
        color:'red',
    },
    HERONMARK_L: {
        weight: 43,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:193,
        maxDamage:311,
        heatDamage:78,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:9,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:50,
        energyCost:13,
        damageIco:'explosion',
        color:'red',
    },
    HOT_FLASH: {
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:148,
        maxDamage:228,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:123,
        totalEnergyDamage:24,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:110,
        energyCost:0,
        damageIco:'electric',
        color:'blue',
    },
    LAST_WORDS: {
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage:185,
        maxDamage:285,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:13,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:3,
        push:1,
        heatCost:16,
        energyCost:47,
        damageIco:'electric',
        color:'blue',
    },
    MAGMA_BLAST_L: {
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'rocket',
        minDamage:243,
        maxDamage:463,
        heatDamage:93,
        totalHeatDamage:30,
        coolingDamage:17,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:13,
        psyResistDrain:0,
        uses:1,
        push:1,
        heatCost:31,
        energyCost:0,
        damageIco:'explosion',
        color:'red',
    },
    MALICE_BEAM: {
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage:140,
        maxDamage:236,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:123,
        totalEnergyDamage:24,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:16,
        energyCost:47,
        damageIco:'electric',
        color:'blue',
    },
    MERCY_L: {
        weight: 84,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:197,
        maxDamage:440,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:10,
        uses:3,
        push:1,
        heatCost:0,
        energyCost:0,
        damageIco:'psyhical',
        color:'yellow',
    },
    MORTAL_BULLET_L: {
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:163,
        maxDamage:213,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:123,
        totalEnergyDamage:12,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:0,
        energyCost:31,
        damageIco:'electric',
        color:'blue',
    },
    NIGHTFALL: {
        weight: 49,
        excludes: [],
        type: 'normal',
        attackType: 'bullet',
        minDamage:248,
        maxDamage:366,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:11,
        uses:3,
        push:0,
        heatCost:31,
        energyCost:31,
        damageIco:'psyhical',
        color:'yellow',
    },
    PURIFIER_L: {
        weight: 49,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:163,
        maxDamage:213,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:0,
        energyCost:0,
        damageIco:'psyhical',
        color:'yellow',
    },
    RECKONING_L: {
        weight: 86,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:182,
        maxDamage:406,
        heatDamage:50,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:10,
        psyResistDrain:0,
        uses:3,
        push:1,
        heatCost:31,
        energyCost:0,
        damageIco:'explosion',
        color:'red',
    },
    SERAPHBLADE_L: {
        weight: 49,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:234,
        maxDamage:376,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:12,
        uses:999,
        push:0,
        heatCost:50,
        energyCost:13,
        damageIco:'psyhical',
        color:'yellow',
    },
    SORROW_L: {
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:163,
        maxDamage:213,
        heatDamage:93,
        totalHeatDamage:12,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:31,
        energyCost:0,
        damageIco:'explosion',
        color:'red',
    },
    STORMWEAVER_L: {
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:244,
        maxDamage:319,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:114,
        totalEnergyDamage:32,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:1,
        heatCost:13,
        energyCost:50,
        damageIco:'electric',
        color:'blue',
    },
    SWEETIE_L: {
        weight: 42,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage:159,
        maxDamage:256,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:48,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:10,
        uses:3,
        push:0,
        heatCost:31,
        energyCost:31,
        damageIco:'psyhical',
        color:'yellow',
    },
    TERROR_CRY: {
        weight: 46,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage:214,
        maxDamage:331,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:3,
        push:1,
        heatCost:25,
        energyCost:25,
        damageIco:'psyhical',
        color:'yellow',
    },
    TERRORBLADE_L: {
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:244,
        maxDamage:319,
        heatDamage:86,
        totalHeatDamage:32,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:12,
        uses:999,
        push:1,
        heatCost:50,
        energyCost:13,
        damageIco:'explosion',
        color:'red',
    },
    ULTRABRIGHT: {
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:203,
        maxDamage:265,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:5,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:16,
        energyCost:47,
        damageIco:'electric',
        color:'blue',
    },
    WARHAMMER: {
        weight: 58,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:237,
        maxDamage:398,
        heatDamage:0,
        totalHeatDamage:15,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:15,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:3,
        heatCost:31,
        energyCost:31,
        damageIco:'psyhical',
        color:'yellow',
    },
    VIKING_HAMMER: {
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage:211,
        maxDamage:354,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:114,
        totalEnergyDamage:0,
        energyRegenDamage:17,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:12,
        uses:999,
        push:3,
        heatCost:13,
        energyCost:50,
        damageIco:'electric',
        color:'blue',
    },
    //                                   Top weapons
    BURNING_SHOWER: {
        weight: 80,
        excludes: [],
        type: 'normal',
        attackType: 'multipleRockets',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:173,
        maxDamage:345,
        heatDamage:86,
        totalHeatDamage:0,
        coolingDamage:10,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:12,
        psyResistDrain:0,
        uses:3,
        push:-2,
        heatCost:81,
        energyCost:0,
        damageIco:'explosion',
        color:'red',
    },
    DELERIUM_L: {
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:203,
        maxDamage:265,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:5,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:16,
        energyCost:47,
        damageIco:'electric',
        color:'blue',
    },
    DESERT_FURY_L: {
        weight: 29,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:154,
        maxDamage:224,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:23,
        uses:2,
        push:0,
        heatCost:16,
        energyCost:16,
        damageIco:'psyhical',
        color:'yellow',
    },
    DESERT_SNAKE_L: {
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'topBomb',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:192,
        maxDamage:329,
        heatDamage:71,
        totalHeatDamage:0,
        coolingDamage:7,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:-1,
        heatCost:75,
        energyCost:25,
        damageIco:'explosion',
        color:'red',
    },
    DESOLATION: {
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'rocketUp',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:210,
        maxDamage:310,
        heatDamage:71,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:10,
        psyResistDrain:0,
        uses:3,
        push:-1,
        heatCost:81,
        energyCost:0,
        damageIco:'explosion',
        color:'red',
    },
    FLAMING_SCOPE_L: {
        weight: 21,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:568,
        maxDamage:741,
        heatDamage:212,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:15,
        psyResistDrain:0,
        uses:1,
        push:0,
        heatCost:155,
        energyCost:31,
        damageIco:'explosion',
        color:'red',
    },
    FALCON: {
        weight: 19,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        minDamage:596,
        maxDamage:997,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:1,
        push:0,
        heatCost:22,
        energyCost:22,
        damageIco:'psyhical',
        color:'yellow',
    },
    GRIM_COBRA: {
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage:181,
        maxDamage:290,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:13,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:3,
        push:-1,
        heatCost:16,
        energyCost:47,
        damageIco:'electric',
        color:'blue',
    },
    HYSTERIA: {
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage:150,
        maxDamage:228,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:123,
        totalEnergyDamage:24,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:16,
        energyCost:47,
        damageIco:'electric',
        color:'blue',
    },
    LIGHTNING_SCOPE: {
        weight: 23,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        minDamage:568,
        maxDamage:741,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:283,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:15,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:1,
        push:0,
        heatCost:31,
        energyCost:155,
        damageIco:'electric',
        color:'blue',
    },
    IRON_FRENZY_L: {
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:203,
        maxDamage:265,
        heatDamage:71,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:5,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:47,
        energyCost:16,
        damageIco:'explosion',
        color:'red',
    },
    MIGHTY_CANNON_L: {
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'topBomb',
        minDamage:226,
        maxDamage:387,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:-1,
        heatCost:38,
        energyCost:38,
        damageIco:'psyhical',
        color:'yellow',

    },
    NIGHT_EAGLE: {
        weight: 46,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage:209,
        maxDamage:336,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:3,
        push:-1,
        heatCost:25,
        energyCost:25,
        damageIco:'psyhical',
        color:'yellow',
    },
    RECKLESS_BEAM: {
        weight: 35,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage:188,
        maxDamage:283,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:31,
        energyCost:31,
        damageIco:'psyhical',
        color:'yellow',
    },
    SAVAGERY: {
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage:150,
        maxDamage:228,
        heatDamage:93,
        totalHeatDamage:24,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:0,
        heatCost:47,
        energyCost:16,
        damageIco:'explosion',
        color:'red',
    },
    SPARTAN_CARNAGEL: {
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'bullet',
        minDamage:226,
        maxDamage:387,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:15,
        uses:3,
        push:0,
        heatCost:31,
        energyCost:31,
        damageIco:'psyhical',
        color:'yellow',
    },
    SPINEFALL_L: {
        weight: 67,
        excludes: [],
        type: 'normal',
        attackType: 'topBomb',
        minDamage:192,
        maxDamage:329,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:95,
        totalEnergyDamage:0,
        energyRegenDamage:7,
        eleResDrain:0,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:999,
        push:-1,
        heatCost:25,
        energyCost:75,
        damageIco:'electric',
        color:'blue',
    },
    SUPREME_CANNON: {
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'multipleRockets',
        minDamage:205,
        maxDamage:315,
        heatDamage:71,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:12,
        psyResistDrain:0,
        uses:3,
        push:1,
        heatCost:44,
        energyCost:19,
        damageIco:'explosion',
        color:'red',
    },
    VALIANT_SNIPER_L: {
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        minDamage:135,
        maxDamage:196,
        heatDamage:0,
        totalHeatDamage:0,
        coolingDamage:0,
        energyDamage:189,
        totalEnergyDamage:0,
        energyRegenDamage:13,
        eleResDrain:17,
        explosionResDrain:0,
        psyResistDrain:0,
        uses:2,
        push:0,
        heatCost:0,
        energyCost:31,
        damageIco:'electric',
        color:'blue',
    },
    VANDAL_RAGE: {
        weight: 41,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage:143,
        maxDamage:187,
        heatDamage:44,
        totalHeatDamage:0,
        coolingDamage:46,
        energyDamage:0,
        totalEnergyDamage:0,
        energyRegenDamage:0,
        eleResDrain:0,
        explosionResDrain:20,
        psyResistDrain:0,
        uses:1,
        push:1,
        heatCost:25,
        energyCost:0,
        damageIco:'explosion',
        color:'red',
    },
    //                                        Teleport
    NothingTeleport: {
        weight: 0,
        excludes: [],
        type: 'normal',
    },
    ADVANCED_TELEPORTER: {
        weight: 11,
        excludes: [],
        type: 'normal',
    },
    DOUBLE_TELEPORT: {
        weight: 26,
        excludes: [],
        type: 'normal',
    },
    //                                          Drones
    ANGUISH: {
        weight: 30,
        excludes: [],
        type: 'normal',
    },
    CLASH: {
        weight: 43,
        excludes: [],
        type: 'normal',
    },
    DUSTMAKER: {
        weight: 29,
        excludes: [],
        type: 'normal',
    },
    FACE_SHOCKER: {
        weight: 41,
        excludes: [],
        type: 'normal',
    },
    HEAT_POINT: {
        weight: 51,
        excludes: [],
        type: 'normal',
    },
    GREEDY: {
        weight: 20,
        excludes: [],
        type: 'normal',
    },
    HURLBAT: {
        weight: 28,
        excludes: [],
        type: 'normal',
    },
    MURMUR: {
        weight: 43,
        excludes: [],
        type: 'normal',
    },
    NEMO: {
        weight: 43,
        excludes: [],
        type: 'normal',
    },
    SHOCKWAVE: {
        weight: 57,
        excludes: [],
        type: 'normal',
    },
    SNACK: {
        weight: 30,
        excludes: [],
        type: 'normal',
    },
    SWOOP: {
        weight: 22,
        excludes: [],
        type: 'normal',
    },
    TORMENT: {
        weight: 29,
        excludes: [],
        type: 'normal',
    },
    VOID: {
        weight: 29,
        excludes: [],
        type: 'normal',
    },
    WINDFORGE: {
        weight: 27,
        excludes: [],
        type: 'normal',
    },
    FLAMEWAVE: {
        weight: 53,
        excludes: [],
        type: 'normal',
    },
    BACKSTABBER: {
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    //                                      Special items
    NothingCharge: {
        weight: 0,
        excludes: [],
        type: 'normal',
    },
    CHARGE_ENGINE: {
        weight: 20,
        excludes: [],
        type: 'normal',
    },
    //                                          Hooks
    NothingHook: {
        weight: 0,
        excludes: [],
        type: 'normal',
    },
    FLAMING_GRAPPLING_HOOK_L: {
        weight: 16,
        excludes: [],
        type: 'normal',
    },
    PLATINUM_GRAPPLING_HOOK_L: {
        weight: 17,
        excludes: [],
        type: 'normal',
    },
    SHOCKING_GRAPPLING_HOOK_L: {
        weight: 11,excludes: [],
        type: 'normal',
    },
};
var arenaStats = {
    procent0: 0,
    procent1: 1,
    procent3: 3,
    procent5: 5,
    procent6: 6,
    procent7: 7,
    procent9: 9,
    procent10: 10,
    procent11: 11,
    procent13: 13,
    procent14: 14,
    procent15: 15,
    procent17: 17,
    procent18: 18,
    procent20: 20,
    procent22: 22,
    procent26: 26,
    procent30: 30,
    procent34: 34,
    procent40: 40,
    level0:0,
    level1:20,
    level2:40,
    level3:60,
    level4:90,
    level5:120,
    level6:150,
    level7:180,
    level8:220,
    level9:260,
    level10:300,
};
var spanHp = document.getElementById("spanHp");
var spanHeat = document.getElementById("spanHeat");
var spanCooling = document.getElementById("spanCooling");
var spanEnergy = document.getElementById("spanEnergy");
var spanEngRegen = document.getElementById("spanEngRegen");
var spanExpRes = document.getElementById("spanExpRes");
var spanEleRes = document.getElementById("spanEleRes");
var spanPysRes = document.getElementById("spanPysRes");
var spanWalking = document.getElementById("spanWalking");
var spanJumping = document.getElementById("spanJumping");
var spanWeight = document.getElementById("spanWeight");
var spanWeightStatic = document.getElementById("spanWeightStatic");
var armourSelectDd = document.getElementById("armourSelectDd");
var legsSelectDd = document.getElementById("legsSelectDd");
var module1SelectDd = document.getElementById("module1SelectDd");
var module2SelectDd = document.getElementById("module2SelectDd");
var module3SelectDd = document.getElementById("module3SelectDd");
var module4SelectDd = document.getElementById("module4SelectDd");
var module5SelectDd = document.getElementById("module5SelectDd");
var module6SelectDd = document.getElementById("module6SelectDd");
var module7SelectDd = document.getElementById("module7SelectDd");
var module8SelectDd = document.getElementById("module8SelectDd");
var sideWep1SelectDd = document.getElementById("sideWep1SelectDd");
var sideWep2SelectDd = document.getElementById("sideWep2SelectDd");
var sideWep3SelectDd = document.getElementById("sideWep3SelectDd");
var sideWep4SelectDd = document.getElementById("sideWep4SelectDd");
var topWep1SelectDd = document.getElementById("topWep1SelectDd");
var topWep2SelectDd = document.getElementById("topWep2SelectDd");
var teleportSelectDd = document.getElementById("teleportSelectDd");
var droneSelectDd = document.getElementById("droneSelectDd");
var chargeSelectDd = document.getElementById("chargeSelectDd");
var hookSelectDd = document.getElementById("hookSelectDd");
var ArenaHeatSelectDd = document.getElementById("ArenaHeatSelectDd");
var ArenaCoolingSelectDd = document.getElementById("ArenaCoolingSelectDd");
var ArenaEnergySelectDd = document.getElementById("ArenaEnergySelectDd");
var ArenaEngReSelectDd = document.getElementById("ArenaEngReSelectDd");
var ArenaExpReSelectDd = document.getElementById("ArenaExpReSelectDd");
var ArenaEleReSelectDd = document.getElementById("ArenaEleReSelectDd");
var ArenaPysReSelectDd = document.getElementById("ArenaPysReSelectDd");
var arenaTotalHpSelectDd = document.getElementById("arenaTotalHpSelectDd");


function changeStats() {
    changerHpStats();
    changeHeatStats();
    changeCoolingStats();
    changeEnergyStats();
    changeEnergyRegenStats();
    changePsyResistStats();
    changeElectricResistStats();
    changeExplosionResistStats();
    changeWeightStats();
    changeWalkingStats();
    changeJumpingStats();
    changeWeightSpanColor();
}
function changerHpStats() {
    // select value from items in a variabile (step 1)
    var hpArmourFromitems = items[armourSelectDd.value];
    var hpLegsFromItems = items[legsSelectDd.value];
    var hpModul1FrItems = items[module1SelectDd.value];
    var hpModul2FrItems = items[module2SelectDd.value];
    var hpModul3FrItems = items[module3SelectDd.value];
    var hpModul4FrItems = items[module4SelectDd.value];
    var hpModul5FrItems = items[module5SelectDd.value];
    var hpModul6FrItems = items[module6SelectDd.value];
    var hpModul7FrItems = items[module7SelectDd.value];
    var hpModul8FrItems = items[module8SelectDd.value];
    var hpArenafrArenaStats = arenaStats[arenaTotalHpSelectDd.value]

    // create a variabile that calculate all values from items (step 2)
    var totalHp = hpArmourFromitems.hp + hpLegsFromItems.hp + hpModul1FrItems.hp + hpModul2FrItems.hp +
        hpModul3FrItems.hp + hpModul4FrItems.hp + hpModul5FrItems.hp + hpModul6FrItems.hp + hpModul7FrItems.hp +
        hpModul8FrItems.hp;
    // write the result (step 3)
    spanHp.innerHTML = totalHp + hpArenafrArenaStats;
    spanHp.value = totalHp + hpArenafrArenaStats;
};
function changeHeatStats() {
    // select value from items in a variabile (step 1)
    var heatArmourFromitems = items[armourSelectDd.value];
    var heatModul1FrItems = items[module1SelectDd.value];
    var heatModul2FrItems = items[module2SelectDd.value];
    var heatModul3FrItems = items[module3SelectDd.value];
    var heatModul4FrItems = items[module4SelectDd.value];
    var heatModul5FrItems = items[module5SelectDd.value];
    var heatModul6FrItems = items[module6SelectDd.value];
    var heatModul7FrItems = items[module7SelectDd.value];
    var heatModul8FrItems = items[module8SelectDd.value];
    var arenaHeatProcent = arenaStats[ArenaHeatSelectDd.value];
    // create a variabile that calculate arena procent from all of your items value (step 2)
    var totalHeatByProcent = (((heatArmourFromitems.heat + heatModul1FrItems.heat + heatModul2FrItems.heat +
        heatModul3FrItems.heat + heatModul4FrItems.heat + heatModul5FrItems.heat + heatModul6FrItems.heat +
        heatModul7FrItems.heat + heatModul8FrItems.heat) * arenaHeatProcent) / 100);
    // create a variabile that calculate all values from items + arena procent(step 3)
    var totalHeat = Math.round(totalHeatByProcent) + (heatArmourFromitems.heat + heatModul1FrItems.heat + heatModul2FrItems.heat +
        heatModul3FrItems.heat + heatModul4FrItems.heat + heatModul5FrItems.heat + heatModul6FrItems.heat +
        heatModul7FrItems.heat + heatModul8FrItems.heat);

    // write the result (step 4)
    spanHeat.innerHTML = totalHeat;
    spanHeat.value = totalHeat;

};
function changeCoolingStats() {
    // select value from items in a variabile (step 1)
    var coolingArmourFromitems = items[armourSelectDd.value];
    var coolingModul1FrItems = items[module1SelectDd.value];
    var coolingModul2FrItems = items[module2SelectDd.value];
    var coolingModul3FrItems = items[module3SelectDd.value];
    var coolingModul4FrItems = items[module4SelectDd.value];
    var coolingModul5FrItems = items[module5SelectDd.value];
    var coolingModul6FrItems = items[module6SelectDd.value];
    var coolingModul7FrItems = items[module7SelectDd.value];
    var coolingModul8FrItems = items[module8SelectDd.value];
    var arenaCoolingProcent = arenaStats[ArenaCoolingSelectDd.value]
    // create a variabile that calculate arena procent from all of your items value (step 2)
    var totalCoolingByProcent = (((coolingArmourFromitems.cooling + coolingModul1FrItems.cooling + coolingModul2FrItems.cooling +
        coolingModul3FrItems.cooling + coolingModul4FrItems.cooling + coolingModul5FrItems.cooling + coolingModul6FrItems.cooling +
        coolingModul7FrItems.cooling + coolingModul8FrItems.cooling) * arenaCoolingProcent) / 100);
    // create a variabile that calculate all values from items + arena procent(step 3)
    var totalCooling = Math.round(totalCoolingByProcent) + (coolingArmourFromitems.cooling + coolingModul1FrItems.cooling + coolingModul2FrItems.cooling +
        coolingModul3FrItems.cooling + coolingModul4FrItems.cooling + coolingModul5FrItems.cooling + coolingModul6FrItems.cooling +
        coolingModul7FrItems.cooling + coolingModul8FrItems.cooling);
    // write the result (step 4)
    spanCooling.innerHTML = totalCooling;
    spanCooling.value = totalCooling;
};
function changeEnergyStats() {
    // select value from items in a variabile (step 1)
    var energyArmourFromitems = items[armourSelectDd.value];
    var energyModul1FrItems = items[module1SelectDd.value];
    var energyModul2FrItems = items[module2SelectDd.value];
    var energyModul3FrItems = items[module3SelectDd.value];
    var energyModul4FrItems = items[module4SelectDd.value];
    var energyModul5FrItems = items[module5SelectDd.value];
    var energyModul6FrItems = items[module6SelectDd.value];
    var energyModul7FrItems = items[module7SelectDd.value];
    var energyModul8FrItems = items[module8SelectDd.value];
    var arenaEnergyProcent = arenaStats[ArenaEnergySelectDd.value];
    // create a variabile that calculate arena procent from all of your items value (step 2)
    var totalEnergyByProcent = (((energyArmourFromitems.energy + energyModul1FrItems.energy + energyModul2FrItems.energy +
        energyModul3FrItems.energy + energyModul4FrItems.energy + energyModul5FrItems.energy + energyModul6FrItems.energy +
        energyModul7FrItems.energy + energyModul8FrItems.energy) * arenaEnergyProcent) / 100);
    // create a variabile that calculate all values from items + arena procent(step 3)
    var totalEnergy = Math.round(totalEnergyByProcent) + (energyArmourFromitems.energy + energyModul1FrItems.energy + energyModul2FrItems.energy +
        energyModul3FrItems.energy + energyModul4FrItems.energy + energyModul5FrItems.energy + energyModul6FrItems.energy +
        energyModul7FrItems.energy + energyModul8FrItems.energy);
    // write the result (step 4)
    spanEnergy.innerHTML = totalEnergy;
    spanEnergy.value = totalEnergy;

};
function changeEnergyRegenStats() {
    // select value from items in a variabile (step 1)
    var energyReArmourFromitems = items[armourSelectDd.value];
    var energyReModul1FrItems = items[module1SelectDd.value];
    var energyReModul2FrItems = items[module2SelectDd.value];
    var energyReModul3FrItems = items[module3SelectDd.value];
    var energyReModul4FrItems = items[module4SelectDd.value];
    var energyReModul5FrItems = items[module5SelectDd.value];
    var energyReModul6FrItems = items[module6SelectDd.value];
    var energyReModul7FrItems = items[module7SelectDd.value];
    var energyReModul8FrItems = items[module8SelectDd.value];
    var arenaEnergyRegenProcent = arenaStats[ArenaEngReSelectDd.value];
    // create a variabile that calculate arena procent from all of your items value (step 2)
    var totalEngRegenByProcent = (((energyReArmourFromitems.engRegen + energyReModul1FrItems.engRegen + energyReModul2FrItems.engRegen +
        energyReModul3FrItems.engRegen + energyReModul4FrItems.engRegen + energyReModul5FrItems.engRegen + energyReModul6FrItems.engRegen +
        energyReModul7FrItems.engRegen + energyReModul8FrItems.engRegen) * arenaEnergyRegenProcent) / 100);
    // create a variabile that calculate all values from items + arena procent(step 3)
    var totalEngRegen = Math.round(totalEngRegenByProcent) + (energyReArmourFromitems.engRegen + energyReModul1FrItems.engRegen + energyReModul2FrItems.engRegen +
        energyReModul3FrItems.engRegen + energyReModul4FrItems.engRegen + energyReModul5FrItems.engRegen + energyReModul6FrItems.engRegen +
        energyReModul7FrItems.engRegen + energyReModul8FrItems.engRegen);
    // write the result (step 4)
    spanEngRegen.innerHTML = totalEngRegen;
    spanEngRegen.value = totalEngRegen;
};
function changePsyResistStats() {
    // select value from items in a variabile (step 1)
    var psyResArmourFromitems = items[armourSelectDd.value];
    var psyResModul1FrItems = items[module1SelectDd.value];
    var psyResModul2FrItems = items[module2SelectDd.value];
    var psyResModul3FrItems = items[module3SelectDd.value];
    var psyResModul4FrItems = items[module4SelectDd.value];
    var psyResModul5FrItems = items[module5SelectDd.value];
    var psyResModul6FrItems = items[module6SelectDd.value];
    var psyResModul7FrItems = items[module7SelectDd.value];
    var psyResModul8FrItems = items[module8SelectDd.value];
    var arenaPysResistProcent = arenaStats[ArenaPysReSelectDd.value];
    // create a variabile that calculate arena procent from all of your items value (step 2)
    var totalPysResByProcent = (((psyResArmourFromitems.psyResist + psyResModul1FrItems.psyResist + psyResModul2FrItems.psyResist +
        psyResModul3FrItems.psyResist + psyResModul4FrItems.psyResist + psyResModul5FrItems.psyResist + psyResModul6FrItems.psyResist +
        psyResModul7FrItems.psyResist + psyResModul8FrItems.psyResist) * arenaPysResistProcent) / 100);
    // create a variabile that calculate all values from items + arena procent(step 3)
    var totalPysRes = Math.round(totalPysResByProcent) + (psyResArmourFromitems.psyResist + psyResModul1FrItems.psyResist + psyResModul2FrItems.psyResist +
        psyResModul3FrItems.psyResist + psyResModul4FrItems.psyResist + psyResModul5FrItems.psyResist + psyResModul6FrItems.psyResist +
        psyResModul7FrItems.psyResist + psyResModul8FrItems.psyResist);
    // write the result (step 4)
    spanPysRes.innerHTML = totalPysRes;
    spanPysRes.value = totalPysRes;

};
function changeElectricResistStats() {
    // select value from items in a variabile (step 1)
    var eleResArmourFromitems = items[armourSelectDd.value];
    var eleResModul1FrItems = items[module1SelectDd.value];
    var eleResModul2FrItems = items[module2SelectDd.value];
    var eleResModul3FrItems = items[module3SelectDd.value];
    var eleResModul4FrItems = items[module4SelectDd.value];
    var eleResModul5FrItems = items[module5SelectDd.value];
    var eleResModul6FrItems = items[module6SelectDd.value];
    var eleResModul7FrItems = items[module7SelectDd.value];
    var eleResModul8FrItems = items[module8SelectDd.value];
    var arenaEleReProcent = arenaStats[ArenaEleReSelectDd.value];
    // create a variabile that calculate arena procent from all of your items value (step 2)
    var totalElectricResistByProcent = (((eleResArmourFromitems.electricResist + eleResModul1FrItems.electricResist + eleResModul2FrItems.electricResist +
        eleResModul3FrItems.electricResist + eleResModul4FrItems.electricResist + eleResModul5FrItems.electricResist + eleResModul6FrItems.electricResist +
        eleResModul7FrItems.electricResist + eleResModul8FrItems.electricResist) * arenaEleReProcent) / 100);
    // create a variabile that calculate all values from items + arena procent(step 3)
    var totalElectricResist = Math.round(totalElectricResistByProcent) + (eleResArmourFromitems.electricResist + eleResModul1FrItems.electricResist + eleResModul2FrItems.electricResist +
        eleResModul3FrItems.electricResist + eleResModul4FrItems.electricResist + eleResModul5FrItems.electricResist + eleResModul6FrItems.electricResist +
        eleResModul7FrItems.electricResist + eleResModul8FrItems.electricResist)
    // write the result (step 4)
    spanEleRes.innerHTML = totalElectricResist;
    spanEleRes.value = totalElectricResist;

};
function changeExplosionResistStats() {
    // select value from items in a variabile (step 1)
    var expArmourFromitems = items[armourSelectDd.value];
    var expModul1FrItems = items[module1SelectDd.value];
    var expModul2FrItems = items[module2SelectDd.value];
    var expModul3FrItems = items[module3SelectDd.value];
    var expModul4FrItems = items[module4SelectDd.value];
    var expModul5FrItems = items[module5SelectDd.value];
    var expModul6FrItems = items[module6SelectDd.value];
    var expModul7FrItems = items[module7SelectDd.value];
    var expModul8FrItems = items[module8SelectDd.value];
    var arenaExpReProcent = arenaStats[ArenaExpReSelectDd.value];
    // create a variabile that calculate arena procent from all of your items value (step 2)
    var totalExplosionResist = (((expArmourFromitems.explosionResist + expModul1FrItems.explosionResist + expModul2FrItems.explosionResist +
        expModul3FrItems.explosionResist + expModul4FrItems.explosionResist + expModul5FrItems.explosionResist + expModul6FrItems.explosionResist +
        expModul7FrItems.explosionResist + expModul8FrItems.explosionResist) * arenaExpReProcent) / 100);
    // create a variabile that calculate all values from items + arena procent(step 3)
    var totalExplosionResist = Math.round(totalExplosionResist) + (expArmourFromitems.explosionResist + expModul1FrItems.explosionResist + expModul2FrItems.explosionResist +
        expModul3FrItems.explosionResist + expModul4FrItems.explosionResist + expModul5FrItems.explosionResist + expModul6FrItems.explosionResist +
        expModul7FrItems.explosionResist + expModul8FrItems.explosionResist)
    // write the result (step 4)
    spanExpRes.innerHTML = totalExplosionResist;
    spanExpRes.value = totalExplosionResist;

};
function changeWeightStats() {
    // select value from items in a variabile (step 1)
    var weightArmourFromitems = items[armourSelectDd.value];
    var weightlegsFromitems = items[legsSelectDd.value];
    var weightModul1FrItems = items[module1SelectDd.value];
    var weightModul2FrItems = items[module2SelectDd.value];
    var weightModul3FrItems = items[module3SelectDd.value];
    var weightModul4FrItems = items[module4SelectDd.value];
    var weightModul5FrItems = items[module5SelectDd.value];
    var weightModul6FrItems = items[module6SelectDd.value];
    var weightModul7FrItems = items[module7SelectDd.value];
    var weightModul8FrItems = items[module8SelectDd.value];
    var weightSideWep1FrItems = items[sideWep1SelectDd.value];
    var weightSideWep2FrItems = items[sideWep2SelectDd.value];
    var weightSideWep3FrItems = items[sideWep3SelectDd.value];
    var weightSideWep4FrItems = items[sideWep4SelectDd.value];
    var weightTopWep1FrItems = items[topWep1SelectDd.value];
    var weightTopWep2FrItems = items[topWep2SelectDd.value];
    var weightTeleportFrItems = items[teleportSelectDd.value];
    var weightDroneFrItems = items[droneSelectDd.value];
    var weightChargeFrItems = items[chargeSelectDd.value];
    var weightHookFrItems = items[hookSelectDd.value];

    // create a variabile that calculate all values from items (step 2)
    var totalWeight = weightArmourFromitems.weight + weightlegsFromitems.weight + weightModul1FrItems.weight +
        weightModul2FrItems.weight + weightModul3FrItems.weight + weightModul4FrItems.weight +
        weightModul5FrItems.weight + weightModul6FrItems.weight + weightModul7FrItems.weight +
        weightModul8FrItems.weight + weightSideWep1FrItems.weight + weightSideWep2FrItems.weight +
        weightSideWep3FrItems.weight + weightSideWep4FrItems.weight + weightTopWep1FrItems.weight +
        weightTopWep2FrItems.weight + weightTeleportFrItems.weight + weightDroneFrItems.weight +
        weightChargeFrItems.weight + weightHookFrItems.weight;
    // write the result (step 3)
    spanWeight.innerHTML = totalWeight;
    spanWeight.value = totalWeight;
};
function changeWalkingStats() {
    var walkLegsFromitems = items[legsSelectDd.value];
    spanWalking.innerHTML = walkLegsFromitems.walking;
};
function changeJumpingStats() {
    var jumpLegsFromitems = items[legsSelectDd.value];
    spanJumping.innerHTML = jumpLegsFromitems.jumping;
};
function changeWeightSpanColor() {
    if (spanWeight.value > 1000) {
        spanWeight.style.color = "red";
        spanWeightStatic.style.color = "red";
    } if (spanWeight.value <= 1000) {
        spanWeight.style.color = "green";
        spanWeightStatic.style.color = "green";
    } if (spanWeight.value == 0) {
        spanWeight.style.color = "black";
        spanWeightStatic.style.color = "black";
    }
}